language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
dist: trusty
env:
  global:
  - PINS="mirage-fs:. mirage-fs-lwt:."
  matrix:
  - OCAML_VERSION=4.04 PACKAGE="mirage-fs-lwt"
  - OCAML_VERSION=4.06 PACKAGE="mirage-fs-lwt"
